name: Test
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  sequences:
    name: Sequence Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Setup GHC
        uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: '9.12.2'

      - name: Dry run for cache key
        run: 'cabal test 0315-sequence-tests --dry-run'
      
      - name: Cache
        uses: actions/cache@v4
        env:
          platform: ubuntu
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
            cache/sequences
          key: sequence-tests-${{ hashFiles('dist-newstyle/cache/plan.json') }}
          restore-keys: |
            sequence-tests-
            
      - name: Test
        run: 'cabal test 0315-sequence-tests'